// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwm7qGljyLYanDanIvetY77TZeQ9wzKJ8',
    appId: '1:454009708779:web:33c5918bb8771226acdeae',
    messagingSenderId: '454009708779',
    projectId: 'flavorhive-2023',
    authDomain: 'flavorhive-2023.firebaseapp.com',
    databaseURL: 'https://flavorhive-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flavorhive-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCxrVYekE8JTOPkxgISxYgOhv2XuS5B0',
    appId: '1:454009708779:android:a3481f023153afacacdeae',
    messagingSenderId: '454009708779',
    projectId: 'flavorhive-2023',
    databaseURL: 'https://flavorhive-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flavorhive-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACsJ5TT6QGPCveij2_YOw2BPAE6lOnGik',
    appId: '1:454009708779:ios:acfac7a2c4ccddcfacdeae',
    messagingSenderId: '454009708779',
    projectId: 'flavorhive-2023',
    databaseURL: 'https://flavorhive-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flavorhive-2023.appspot.com',
    iosBundleId: 'com.example.flavorHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACsJ5TT6QGPCveij2_YOw2BPAE6lOnGik',
    appId: '1:454009708779:ios:622a0d3dbe81b6a3acdeae',
    messagingSenderId: '454009708779',
    projectId: 'flavorhive-2023',
    databaseURL: 'https://flavorhive-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flavorhive-2023.appspot.com',
    iosBundleId: 'com.example.flavorHive.RunnerTests',
  );
}
